"""
Django settings for camri_pjo project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yaie8^j25v%v^&@!3(y35b(pg$2_--$x%0^(38ik4(!!0&wt=0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pjo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'camri_pjo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'camri_pjo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pjo_db',
        'USER': 'camridb_admin',
        'PASSWORD': 'Admin1234!',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MESSAGE_LEVEL = 10  # DEBUG
#MESSAGE_LEVEL = 20  # INFO

# LOG

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'simple': {
            'format': '[%(levelname)s]%(module)s.%(funcName)s(line:%(lineno)d) %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'verbose': {
            'format': '[%(asctime)s][%(levelname)s]%(module)s.%(funcName)s(line:%(lineno)d) %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'dbFormat': {
            'format': '[%(asctime)s]%(module)s.%(funcName)s(line:%(lineno)d) \n %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'errFormat': {
            'format': '[%(asctime)s][%(levelname)s]%(message)s [th:%(thread)d,prc:%(process)d] \n ',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'devLogFile': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/Users/woomi_mac/woomi_projects/camri_pjo/pjoLog/pjoDev.log',
            'formatter': 'verbose'
        },
        'dbLogFile': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/Users/woomi_mac/woomi_projects/camri_pjo/pjoLog/pjoDB.log',
            'formatter': 'dbFormat'
        },
        'errLogFile': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': '/Users/woomi_mac/woomi_projects/camri_pjo/pjoLog/pjoError.log',
            'formatter': 'errFormat'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'WARNING',
        },
        'django.request': {
            'handlers': ['console'],
            # 'handlers': ['console', 'errLogFile'],
            'propagate': False,
            'level': 'WARNING',
        },
        'dba': {
            'handlers': ['console'],
            # 'handlers': ['console', 'dbLogFile'],
            'level': 'DEBUG',
        },
        'devLog': {
            'handlers': ['console'],
            # 'handlers': ['console', 'devLogFile'],
            'level': 'DEBUG',
        },
        'errLog': {
            'handlers': ['console'],
            # 'handlers': ['console', 'errLogFile'],
            'level': 'WARNING',
        },
    }
}
